# Generated by Django 5.0 on 2024-01-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_alter_log_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='succesful',
            field=models.BooleanField(default=False),
        ),
    ]
